version: "3.1"

services:
  api:
    container_name: api
    build: ./
    command: npm run start
    restart: always
    ports:
      - "3000:3000"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=rahatik
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  webserver:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
      - ./nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - api
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    depends_on:
      - webserver
    volumes:
      - www-html:/var/www/html
      - etc-letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/var/www/html --email almas@gmail.com  --agree-tos --no-eff-email -d back-sezin.devup.kz

volumes:
  pgdata:
